# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "edbd0c2ea55db55368b4365802de0b43"
name = "floodlight-reviews"
handle = "floodlight-reviews"
application_url = "https://anne-impressed-rca-levels.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "floodlight-design-2024.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,write_products"

[auth]
redirect_urls = [
  "https://anne-impressed-rca-levels.trycloudflare.com/auth/callback",
  "https://anne-impressed-rca-levels.trycloudflare.com/auth/shopify/callback",
  "https://anne-impressed-rca-levels.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
